apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "mcp-server-groupoffice.fullname" . }}
  labels:
    {{- include "mcp-server-groupoffice.labels" . | nindent 4 }}
stringData:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
